### ISSUE TITLE
[FE] 색상선택 페이지 버그 해결

### ISSUE THREAD

**Issue by meanz1** [softeerbootcamp-2nd/A4-FourEver#132]
## 📝 Description

색상선택 페이지에서 360도 구현했을 때 경로를 parsing해주는데, 
외장 생상인지 내장 색상인지에 따른 경우값 설정을 해주지 않아 내장색상 선택을 클릭하면 오류가 나타납니다.

## 🌟 Tasks

- [x] 버그해결
+ /fixError

**Comment by hwangJN** [comment]
Color.js 에서 RotateImg 컴포넌트 부분에 이런식으로 해주면 오류 안나요! 

```javascript
      {activeColorFiled === MYCAR.COLOR.FILED.EXCOLOR ? (
          <RotateImg selectedOption={selectedOption}></RotateImg>
        ) : (
          <TrimImg
            src={selectedOption[MYCAR.COLOR.FILED.IMG[activeColorFiled]]}
          />
       )}

```

근데 외장색상 360도 컨테이너 width가 700이고 내장색상(TrimImg) width 는 620이라서 왔다갔다 선택하면 너무 부자연스러워서 width 통일이 필요할 것 같아요~~!

**Comment by meanz1** [comment]
> Color.js 에서 RotateImg 컴포넌트 부분에 이런식으로 해주면 오류 안나요!
> 
> ```js
>       {activeColorFiled === MYCAR.COLOR.FILED.EXCOLOR ? (
>           <RotateImg selectedOption={selectedOption}></RotateImg>
>         ) : (
>           <TrimImg
>             src={selectedOption[MYCAR.COLOR.FILED.IMG[activeColorFiled]]}
>           />
>        )}
> ```
> 
> 근데 외장색상 360도 컨테이너 width가 700이고 내장색상(TrimImg) width 는 620이라서 왔다갔다 선택하면 너무 부자연스러워서 width 통일이 필요할 것 같아요~~!

오 감사합니다 ~~ 반영해서 fix해놓을게요 !!
